import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps() {
  const response = await fetch('https://zorcmspowc.execute-api.ap-northeast-2.amazonaws.com/prod/quote');
  const data = await response.json();

  console.log(`Server-side rendered page: "${data.message}"`);
  return {
    props: {
      quote: data
    }
  }
}

export default function Home({quote}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
            <div className={styles.card}>
                <h1>SSR</h1>
            </div>
            <div className={styles.center}>
                <div className={styles.description}>
                    { quote ? (
                            <p>{quote.message}</p>
                        ) : ( 
                            <p>Loading ...</p>
                        )
                    }
                </div>
            </div>
            <div>
                <a href="/">client-side rendered page 에서 보기</a>
            </div>
        </main>
    </>
  )
}
